Repository Code-A2Z/code-a2z, pull requests merged in 2024-10, with the labels that each got.

#822 Added Google Search Clone
  Front-end-Projects/Basic/Google-Search-Clone/README.md
  Front-end-Projects/Basic/Google-Search-Clone/advsrch.html
  Front-end-Projects/Basic/Google-Search-Clone/favi.png
  Front-end-Projects/Basic/Google-Search-Clone/googleimage.png
  Front-end-Projects/Basic/Google-Search-Clone/home.jpg
  Front-end-Projects/Basic/Google-Search-Clone/imagesrch.html
  Front-end-Projects/Basic/Google-Search-Clone/index.html
  Front-end-Projects/Basic/Google-Search-Clone/screenshot.webp
  Front-end-Projects/Basic/Google-Search-Clone/style.css
  Front-end-Projects/README.md
Labels: Requested Changes ⚙️

#847 Added Qr code generator
  Vanilla-JS-Projects/Basic/Qr-Code-Generator/README.MD
  Vanilla-JS-Projects/Basic/Qr-Code-Generator/index.html
  Vanilla-JS-Projects/Basic/Qr-Code-Generator/screenshot.webp
  Vanilla-JS-Projects/Basic/Qr-Code-Generator/script.js
  Vanilla-JS-Projects/Basic/Qr-Code-Generator/style.css
  Vanilla-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#842 Added Amazon Frontend Clone Project
  Vanilla-JS-Projects/Intermediate/Amazon-Clone/README.md
  Vanilla-JS-Projects/Intermediate/Amazon-Clone/images/amazon.png
  Vanilla-JS-Projects/Intermediate/Amazon-Clone/images/carousel1.png
  Vanilla-JS-Projects/Intermediate/Amazon-Clone/images/carousel2.png
  Vanilla-JS-Projects/Intermediate/Amazon-Clone/images/carousel3.png
  Vanilla-JS-Projects/Intermediate/Amazon-Clone/images/carousel4.png
  Vanilla-JS-Projects/Intermediate/Amazon-Clone/images/favicon.png
  Vanilla-JS-Projects/Intermediate/Amazon-Clone/images/flag.png
  Vanilla-JS-Projects/Intermediate/Amazon-Clone/images/item1.png
  Vanilla-JS-Projects/Intermediate/Amazon-Clone/images/item2.png
  Vanilla-JS-Projects/Intermediate/Amazon-Clone/images/item3.png
  Vanilla-JS-Projects/Intermediate/Amazon-Clone/images/item4.png
  Vanilla-JS-Projects/Intermediate/Amazon-Clone/index.html
  Vanilla-JS-Projects/Intermediate/Amazon-Clone/screenshot.webp
  Vanilla-JS-Projects/Intermediate/Amazon-Clone/script.js
  Vanilla-JS-Projects/Intermediate/Amazon-Clone/styles.css
  Vanilla-JS-Projects/README.md
Labels: Requested Changes ⚙️

#816 Added task manager app
  Angular-JS-Projects/Basic/Task-Manager/README.md
  Angular-JS-Projects/Basic/Task-Manager/app.js
  Angular-JS-Projects/Basic/Task-Manager/index.html
  Angular-JS-Projects/Basic/Task-Manager/screenshot.webp
  Angular-JS-Projects/Basic/Task-Manager/style.css
  Angular-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#868 Added a book website
  Front-end-Projects/Intermediate/Book-Website/README.md
  Front-end-Projects/Intermediate/Book-Website/images/background.png
  Front-end-Projects/Intermediate/Book-Website/images/book1.png
  Front-end-Projects/Intermediate/Book-Website/images/book2.png
  Front-end-Projects/Intermediate/Book-Website/images/book3.png
  Front-end-Projects/Intermediate/Book-Website/images/book4.png
  Front-end-Projects/Intermediate/Book-Website/images/book5.png
  Front-end-Projects/Intermediate/Book-Website/images/logo.png
  Front-end-Projects/Intermediate/Book-Website/images/mainbook.png
  Front-end-Projects/Intermediate/Book-Website/index.html
  Front-end-Projects/Intermediate/Book-Website/screenshot.webp
  Front-end-Projects/Intermediate/Book-Website/style.css
  Front-end-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#860 Netflix Clone Project Added
  React-JS-Projects/Intermediate/Netflix-Clone/README.md
  React-JS-Projects/Intermediate/Netflix-Clone/package-lock.json
  React-JS-Projects/Intermediate/Netflix-Clone/package.json
  React-JS-Projects/Intermediate/Netflix-Clone/public/index.html
  React-JS-Projects/Intermediate/Netflix-Clone/public/manifest.json
  React-JS-Projects/Intermediate/Netflix-Clone/public/robots.txt
  React-JS-Projects/Intermediate/Netflix-Clone/screenshot.webp
  React-JS-Projects/Intermediate/Netflix-Clone/src/App.css
  React-JS-Projects/Intermediate/Netflix-Clone/src/App.js
  React-JS-Projects/Intermediate/Netflix-Clone/src/Components/Banner/Banner.css
  React-JS-Projects/Intermediate/Netflix-Clone/src/Components/Banner/Banner.js
  React-JS-Projects/Intermediate/Netflix-Clone/src/Components/Footer/Footer.css
  React-JS-Projects/Intermediate/Netflix-Clone/src/Components/Footer/Footer.js
  React-JS-Projects/Intermediate/Netflix-Clone/src/Components/NavBar/NavBar.css
  React-JS-Projects/Intermediate/Netflix-Clone/src/Components/NavBar/NavBar.js
  React-JS-Projects/Intermediate/Netflix-Clone/src/Components/RowPost/RowPost.css
  React-JS-Projects/Intermediate/Netflix-Clone/src/Components/RowPost/RowPost.js
  React-JS-Projects/Intermediate/Netflix-Clone/src/Constants/Constants.js
  React-JS-Projects/Intermediate/Netflix-Clone/src/axios.js
  React-JS-Projects/Intermediate/Netflix-Clone/src/index.js
  React-JS-Projects/Intermediate/Netflix-Clone/src/urls.js
  React-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️, Follow Guidelines ✒️

#854 Added Hotstar Clone
  Front-end-Projects/Intermediate/Hotstar-Clone/Hotstar.png
  Front-end-Projects/Intermediate/Hotstar-Clone/README.md
  Front-end-Projects/Intermediate/Hotstar-Clone/images/add.png
  Front-end-Projects/Intermediate/Hotstar-Clone/images/disney.PNG
  Front-end-Projects/Intermediate/Hotstar-Clone/images/geographic.PNG
  Front-end-Projects/Intermediate/Hotstar-Clone/images/logo.png
  Front-end-Projects/Intermediate/Hotstar-Clone/images/marvel.PNG
  Front-end-Projects/Intermediate/Hotstar-Clone/images/nxt.png
  Front-end-Projects/Intermediate/Hotstar-Clone/images/pixar.PNG
  Front-end-Projects/Intermediate/Hotstar-Clone/images/play.png
  Front-end-Projects/Intermediate/Hotstar-Clone/images/poster 1.png
  Front-end-Projects/Intermediate/Hotstar-Clone/images/poster 10.png
  Front-end-Projects/Intermediate/Hotstar-Clone/images/poster 11.png
  Front-end-Projects/Intermediate/Hotstar-Clone/images/poster 12.png
  Front-end-Projects/Intermediate/Hotstar-Clone/images/poster 2.png
  Front-end-Projects/Intermediate/Hotstar-Clone/images/poster 3.png
  Front-end-Projects/Intermediate/Hotstar-Clone/images/poster 4.png
  Front-end-Projects/Intermediate/Hotstar-Clone/images/poster 5.png
  Front-end-Projects/Intermediate/Hotstar-Clone/images/poster 6.png
  Front-end-Projects/Intermediate/Hotstar-Clone/images/poster 7.png
  Front-end-Projects/Intermediate/Hotstar-Clone/images/poster 8.png
  Front-end-Projects/Intermediate/Hotstar-Clone/images/poster 9.png
  Front-end-Projects/Intermediate/Hotstar-Clone/images/pre.png
  Front-end-Projects/Intermediate/Hotstar-Clone/images/slider 1.PNG
  Front-end-Projects/Intermediate/Hotstar-Clone/images/slider 2.PNG
  Front-end-Projects/Intermediate/Hotstar-Clone/images/slider 3.PNG
  Front-end-Projects/Intermediate/Hotstar-Clone/images/slider 4.PNG
  Front-end-Projects/Intermediate/Hotstar-Clone/images/slider 5.PNG
  Front-end-Projects/Intermediate/Hotstar-Clone/images/star-wars.PNG
  Front-end-Projects/Intermediate/Hotstar-Clone/index.html
  Front-end-Projects/Intermediate/Hotstar-Clone/index.js
  Front-end-Projects/Intermediate/Hotstar-Clone/screenshot.webp
  Front-end-Projects/Intermediate/Hotstar-Clone/styles.css
  Front-end-Projects/Intermediate/Hotstar-Clone/videos/disney.mp4
  Front-end-Projects/Intermediate/Hotstar-Clone/videos/geographic.mp4
  Front-end-Projects/Intermediate/Hotstar-Clone/videos/marvel.mp4
  Front-end-Projects/Intermediate/Hotstar-Clone/videos/pixar.mp4
  Front-end-Projects/Intermediate/Hotstar-Clone/videos/star-war.mp4
  Front-end-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#888 Added Personal portfolio to Vanilla-Js
  Vanilla-JS-Projects/Basic/Personal-Portfolio/README.md
  Vanilla-JS-Projects/Basic/Personal-Portfolio/index.html
  Vanilla-JS-Projects/Basic/Personal-Portfolio/picture.jpg
  Vanilla-JS-Projects/Basic/Personal-Portfolio/project1.png
  Vanilla-JS-Projects/Basic/Personal-Portfolio/project2.avif
  Vanilla-JS-Projects/Basic/Personal-Portfolio/project3.jpg
  Vanilla-JS-Projects/Basic/Personal-Portfolio/screenshot.webp
  Vanilla-JS-Projects/Basic/Personal-Portfolio/script.js
  Vanilla-JS-Projects/Basic/Personal-Portfolio/style.css
  Vanilla-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#890 Added sudoku-solver
  React-JS-Projects/Advanced/Sudoku-Solver/.eslintrc.cjs
  React-JS-Projects/Advanced/Sudoku-Solver/README.md
  React-JS-Projects/Advanced/Sudoku-Solver/index.html
  React-JS-Projects/Advanced/Sudoku-Solver/package-lock.json
  React-JS-Projects/Advanced/Sudoku-Solver/package.json
  React-JS-Projects/Advanced/Sudoku-Solver/public/vite.svg
  React-JS-Projects/Advanced/Sudoku-Solver/screenshot.webp
  React-JS-Projects/Advanced/Sudoku-Solver/src/App.css
  React-JS-Projects/Advanced/Sudoku-Solver/src/App.jsx
  React-JS-Projects/Advanced/Sudoku-Solver/src/assets/logo1.png
  React-JS-Projects/Advanced/Sudoku-Solver/src/assets/react.svg
  React-JS-Projects/Advanced/Sudoku-Solver/src/assets/try_it.png
  React-JS-Projects/Advanced/Sudoku-Solver/src/index.css
  React-JS-Projects/Advanced/Sudoku-Solver/src/index.jsx
  React-JS-Projects/Advanced/Sudoku-Solver/src/main.jsx
  React-JS-Projects/Advanced/Sudoku-Solver/vite.config.js
  React-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️, Follow Guidelines ✒️

#880 Added N-Queen Visualizer | Issue #825
  Vanilla-JS-Projects/Advanced/N-Queen-Visualizer/README.md
  Vanilla-JS-Projects/Advanced/N-Queen-Visualizer/chess.js
  Vanilla-JS-Projects/Advanced/N-Queen-Visualizer/index.css
  Vanilla-JS-Projects/Advanced/N-Queen-Visualizer/index.html
  Vanilla-JS-Projects/Advanced/N-Queen-Visualizer/screenshot.webp
  Vanilla-JS-Projects/README.md
Labels: Requested Changes ⚙️, Follow Guidelines ✒️

#889 Update UI and Styling for Contact Management App
  Angular-JS-Projects/Advanced/Contact-Manager/README.md
  Angular-JS-Projects/Advanced/Contact-Manager/angular.json
  Angular-JS-Projects/Advanced/Contact-Manager/db.json
  Angular-JS-Projects/Advanced/Contact-Manager/images/image01.png
  Angular-JS-Projects/Advanced/Contact-Manager/images/image02.png
  Angular-JS-Projects/Advanced/Contact-Manager/images/image03.png
  Angular-JS-Projects/Advanced/Contact-Manager/images/image04.png
  Angular-JS-Projects/Advanced/Contact-Manager/images/image05.png
  Angular-JS-Projects/Advanced/Contact-Manager/package-lock.json
  Angular-JS-Projects/Advanced/Contact-Manager/package.json
  Angular-JS-Projects/Advanced/Contact-Manager/screenshot.webp
  Angular-JS-Projects/Advanced/Contact-Manager/src/app/app.component.html
  Angular-JS-Projects/Advanced/Contact-Manager/src/app/app.component.ts
  Angular-JS-Projects/Advanced/Contact-Manager/src/app/app.config.ts
  Angular-JS-Projects/Advanced/Contact-Manager/src/app/components/contact-list/contact-list.component.html
  Angular-JS-Projects/Advanced/Contact-Manager/src/app/components/contact-list/contact-list.component.ts
  Angular-JS-Projects/Advanced/Contact-Manager/src/app/components/edit-contact/edit-contact.component.html
  Angular-JS-Projects/Advanced/Contact-Manager/src/app/components/edit-contact/edit-contact.component.ts
  Angular-JS-Projects/Advanced/Contact-Manager/src/app/components/header/header.component.html
  Angular-JS-Projects/Advanced/Contact-Manager/src/app/components/header/header.component.ts
  Angular-JS-Projects/Advanced/Contact-Manager/src/app/components/new-contact/new-contact.component.html
  Angular-JS-Projects/Advanced/Contact-Manager/src/app/components/new-contact/new-contact.component.ts
  Angular-JS-Projects/Advanced/Contact-Manager/src/app/services/contact.service.ts
  Angular-JS-Projects/Advanced/Contact-Manager/src/assets/images/bg-2.jpeg
  Angular-JS-Projects/Advanced/Contact-Manager/src/styles.css
  Angular-JS-Projects/Advanced/Contact-Manager/tailwind.config.js
Labels: bug 🐛, Requested Changes ⚙️

#909 Added Recipe Sharing project
  Angular-JS-Projects/Intermediate/Recipe-Sharing/.gitignore
  Angular-JS-Projects/Intermediate/Recipe-Sharing/README.md
  Angular-JS-Projects/Intermediate/Recipe-Sharing/package-lock.json
  Angular-JS-Projects/Intermediate/Recipe-Sharing/package.json
  Angular-JS-Projects/Intermediate/Recipe-Sharing/screenshot.webp
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/Product.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/Recipe.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/app-routing.module.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/app.component.css
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/app.component.html
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/app.component.spec.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/app.component.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/app.module.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/eshop/eshop.component.css
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/eshop/eshop.component.html
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/eshop/eshop.component.spec.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/eshop/eshop.component.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/form.service.spec.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/form.service.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/home/home.component.css
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/home/home.component.html
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/home/home.component.spec.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/home/home.component.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/navbar/navbar.component.css
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/navbar/navbar.component.html
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/navbar/navbar.component.spec.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/navbar/navbar.component.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/recipe-form/recipe-form.component.css
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/recipe-form/recipe-form.component.html
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/recipe-form/recipe-form.component.spec.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/recipe-form/recipe-form.component.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/shop.service.spec.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/shop.service.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/update-recipe-form/update-recipe-form.component.css
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/update-recipe-form/update-recipe-form.component.html
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/update-recipe-form/update-recipe-form.component.spec.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/update-recipe-form/update-recipe-form.component.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/view-recipe/view-recipe.component.css
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/view-recipe/view-recipe.component.html
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/view-recipe/view-recipe.component.spec.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/app/view-recipe/view-recipe.component.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/assets/cooking-hotpot.png
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/favicon.ico
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/index.html
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/main.ts
  Angular-JS-Projects/Intermediate/Recipe-Sharing/src/styles.css
  Angular-JS-Projects/README.md
Labels: question❓, Requested Changes ⚙️

#915 Added Electronic drum kit Project
  Vanilla-JS-Projects/Basic/Electronic-Drum-Kit/Drum.jpg
  Vanilla-JS-Projects/Basic/Electronic-Drum-Kit/README.md
  Vanilla-JS-Projects/Basic/Electronic-Drum-Kit/assets/boom.wav
  Vanilla-JS-Projects/Basic/Electronic-Drum-Kit/assets/clap.wav
  Vanilla-JS-Projects/Basic/Electronic-Drum-Kit/assets/hihat.wav
  Vanilla-JS-Projects/Basic/Electronic-Drum-Kit/assets/kick.wav
  Vanilla-JS-Projects/Basic/Electronic-Drum-Kit/assets/openhat.wav
  Vanilla-JS-Projects/Basic/Electronic-Drum-Kit/assets/ride.wav
  Vanilla-JS-Projects/Basic/Electronic-Drum-Kit/assets/snare.wav
  Vanilla-JS-Projects/Basic/Electronic-Drum-Kit/assets/tink.wav
  Vanilla-JS-Projects/Basic/Electronic-Drum-Kit/assets/tom.wav
  Vanilla-JS-Projects/Basic/Electronic-Drum-Kit/index.html
  Vanilla-JS-Projects/Basic/Electronic-Drum-Kit/screenshot.webp
  Vanilla-JS-Projects/Basic/Electronic-Drum-Kit/script.js
  Vanilla-JS-Projects/Basic/Electronic-Drum-Kit/style.css
  Vanilla-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#928 Add Wikipedia clone
  Vanilla-JS-Projects/Intermediate/Wikipedia-Clone/README.md
  Vanilla-JS-Projects/Intermediate/Wikipedia-Clone/index.html
  Vanilla-JS-Projects/Intermediate/Wikipedia-Clone/screenshot.webp
  Vanilla-JS-Projects/Intermediate/Wikipedia-Clone/script.js
  Vanilla-JS-Projects/Intermediate/Wikipedia-Clone/style.css
  Vanilla-JS-Projects/README.md
Labels: Requested Changes ⚙️

#943 Added ProgressBar | Issue #879
  webmasterlog/src/app/globals.css
  webmasterlog/src/components/MainContent.tsx
  webmasterlog/src/components/shared/ProgressBar.tsx
Labels: Requested Changes ⚙️

#851 Added Calendar App
  Vanilla-JS-Projects/Intermediate/Calendar-App/IMG/down-arrow.svg
  Vanilla-JS-Projects/Intermediate/Calendar-App/IMG/left.svg
  Vanilla-JS-Projects/Intermediate/Calendar-App/IMG/right.svg
  Vanilla-JS-Projects/Intermediate/Calendar-App/README.md
  Vanilla-JS-Projects/Intermediate/Calendar-App/app.js
  Vanilla-JS-Projects/Intermediate/Calendar-App/index.html
  Vanilla-JS-Projects/Intermediate/Calendar-App/screenshot.webp
  Vanilla-JS-Projects/Intermediate/Calendar-App/style.css
  Vanilla-JS-Projects/Intermediate/Calendar-App/utility.css
  Vanilla-JS-Projects/README.md
Labels: Requested Changes ⚙️

#912 Completed File Upload and Download System using Node JS #46
  Node-JS-Projects/Intermediate/File-Upload-And-Download-System/.gitignore
  Node-JS-Projects/Intermediate/File-Upload-And-Download-System/README.md
  Node-JS-Projects/Intermediate/File-Upload-And-Download-System/index.js
  Node-JS-Projects/Intermediate/File-Upload-And-Download-System/package-lock.json
  Node-JS-Projects/Intermediate/File-Upload-And-Download-System/package.json
  Node-JS-Projects/Intermediate/File-Upload-And-Download-System/public/css/styles.css
  Node-JS-Projects/Intermediate/File-Upload-And-Download-System/screenshot.webp
  Node-JS-Projects/Intermediate/File-Upload-And-Download-System/views/index.ejs
  Node-JS-Projects/README.md
Labels: Requested Changes ⚙️

#916 Added Gen AI Quiz Application with Gemini LLM in Next JS
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/README.md
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/components.json
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/next-env.d.ts
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/next.config.js
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/package-lock.json
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/package.json
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/postcss.config.js
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/public/logo.ico
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/public/next.svg
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/public/vercel.svg
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/screenshot.webp
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/src/app/favicon.ico
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/src/app/globals.css
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/src/app/layout.tsx
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/src/app/page.tsx
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/src/categories.ts
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/src/components/ui/button.tsx
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/src/lib/ai.ts
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/src/lib/common.ts
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/src/lib/utils.ts
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/tailwind.config.js
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/tailwind.config.ts
  Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/tsconfig.json
  Next-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#1010 Text editor
  React-JS-Projects/Intermediate/Text-Editor/README.md
  React-JS-Projects/Intermediate/Text-Editor/Screenshot.webp
  React-JS-Projects/Intermediate/Text-Editor/eslint.config.js
  React-JS-Projects/Intermediate/Text-Editor/index.html
  React-JS-Projects/Intermediate/Text-Editor/package-lock 2.json
  React-JS-Projects/Intermediate/Text-Editor/package-lock.json
  React-JS-Projects/Intermediate/Text-Editor/postcss.config.js
  React-JS-Projects/Intermediate/Text-Editor/src/App.css
  React-JS-Projects/Intermediate/Text-Editor/src/App.jsx
  React-JS-Projects/Intermediate/Text-Editor/src/Components/TextContainer.jsx
  React-JS-Projects/Intermediate/Text-Editor/src/Components/TextEditor.jsx
  React-JS-Projects/Intermediate/Text-Editor/src/Components/UndoRedo.jsx
  React-JS-Projects/Intermediate/Text-Editor/src/assets/react.svg
  React-JS-Projects/Intermediate/Text-Editor/src/index.css
  React-JS-Projects/Intermediate/Text-Editor/src/main.jsx
  React-JS-Projects/Intermediate/Text-Editor/tailwind.config.js
  React-JS-Projects/Intermediate/Text-Editor/vite.config.js
  React-JS-Projects/README.md
Labels: Requested Changes ⚙️
