Repository Code-A2Z/code-a2z, pull requests merged in 2024-05, with the labels that each got.

#126 Weather website
  Next-JS-Projects/Basic/Weather-Website/.eslintrc.json
  Next-JS-Projects/Basic/Weather-Website/.gitignore
  Next-JS-Projects/Basic/Weather-Website/README.md
  Next-JS-Projects/Basic/Weather-Website/app/api/weather/route.ts
  Next-JS-Projects/Basic/Weather-Website/app/favicon.ico
  Next-JS-Projects/Basic/Weather-Website/app/globals.css
  Next-JS-Projects/Basic/Weather-Website/app/layout.tsx
  Next-JS-Projects/Basic/Weather-Website/app/page.module.css
  Next-JS-Projects/Basic/Weather-Website/app/page.tsx
  Next-JS-Projects/Basic/Weather-Website/next.config.mjs
  Next-JS-Projects/Basic/Weather-Website/package-lock.json
  Next-JS-Projects/Basic/Weather-Website/package.json
  Next-JS-Projects/Basic/Weather-Website/postcss.config.mjs
  Next-JS-Projects/Basic/Weather-Website/public/next.svg
  Next-JS-Projects/Basic/Weather-Website/public/vercel.svg
  Next-JS-Projects/Basic/Weather-Website/screenshot.webp
  Next-JS-Projects/Basic/Weather-Website/tailwind.config.ts
  Next-JS-Projects/Basic/Weather-Website/tsconfig.json
  Next-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#132 Stopwatch website
  Vanilla-JS-Projects/Basic/Stopwatch/README.md
  Vanilla-JS-Projects/Basic/Stopwatch/index.html
  Vanilla-JS-Projects/Basic/Stopwatch/screenshot.webp
  Vanilla-JS-Projects/Basic/Stopwatch/script.js
  Vanilla-JS-Projects/Basic/Stopwatch/styles.css
  database/vanilla.json
Labels: bug 🐛, Requested Changes ⚙️

#147 Project Ceaser Cipher Conversion Project
  Vanilla-JS-Projects/Intermediate/Ceaser-Cipher/README.md
  Vanilla-JS-Projects/Intermediate/Ceaser-Cipher/cipher.css
  Vanilla-JS-Projects/Intermediate/Ceaser-Cipher/index.html
  Vanilla-JS-Projects/Intermediate/Ceaser-Cipher/main.js
  Vanilla-JS-Projects/Intermediate/Ceaser-Cipher/screenshot.webp
  Vanilla-JS-Projects/Intermediate/Ceaser-Cipher/style.css
Labels: level2, Approved ✔️, Vanilla-JS 😊, gssoc

#149 Jwt authentication backend
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/README.md
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/images/image-1.png
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/images/image.png
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/images/logout.png
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/images/protectedUser.png
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/images/protected_admin.png
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/images/refresh.png
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/images/register_admin.png
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/package-lock.json
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/package.json
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/screenshot.webp
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/src/app.js
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/src/constants.js
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/src/controllers/user.controller.js
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/src/db/index.js
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/src/index.js
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/src/middlewares/auth.middleware.js
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/src/middlewares/permit.middleware.js
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/src/models/user.model.js
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/src/routes/user.routes.js
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/src/utils/ApiError.js
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/src/utils/ApiResponse.js
  Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles/src/utils/asyncHandler.js
  Node-JS-Projects/README.md
Labels: level2, Approved ✔️, Node-JS 😎, gssoc

#187 UI of card
  src/components/Cards/Card.jsx
  src/components/Cards/ProjectCards.jsx
  src/components/Cards/card.css
Labels: Requested Changes ⚙️

#195 Basic Level Project AngularJS - QuickNotes
  Angular-JS-Projects/Basic/Quick-Notes/README.md
  Angular-JS-Projects/Basic/Quick-Notes/app.js
  Angular-JS-Projects/Basic/Quick-Notes/bg.webp
  Angular-JS-Projects/Basic/Quick-Notes/index.html
  Angular-JS-Projects/Basic/Quick-Notes/screenshot.webp
  Angular-JS-Projects/Basic/Quick-Notes/styles.css
  Angular-JS-Projects/README.md
  Next-JS-Projects/README.md
Labels: level1, Approved ✔️, Angular-JS 🎉, gssoc

#191 Nodejs crud operations
  Node-JS-Projects/Basic/Crud-Operations/.env.example
  Node-JS-Projects/Basic/Crud-Operations/README.md
  Node-JS-Projects/Basic/Crud-Operations/db/config.js
  Node-JS-Projects/Basic/Crud-Operations/package.json
  Node-JS-Projects/Basic/Crud-Operations/public/app.js
  Node-JS-Projects/Basic/Crud-Operations/public/index.html
  Node-JS-Projects/Basic/Crud-Operations/public/style.css
  Node-JS-Projects/Basic/Crud-Operations/screenshot.webp
  Node-JS-Projects/Basic/Crud-Operations/server.js
  Node-JS-Projects/README.md
Labels: Requested Changes ⚙️

#208 Cryptocurrency Finder added
  React-JS-Projects/Intermediate/Cryptocurrency-Finder/.eslintrc.cjs
  React-JS-Projects/Intermediate/Cryptocurrency-Finder/README.md
  React-JS-Projects/Intermediate/Cryptocurrency-Finder/index.html
  React-JS-Projects/Intermediate/Cryptocurrency-Finder/package.json
  React-JS-Projects/Intermediate/Cryptocurrency-Finder/screenshot.webp
  React-JS-Projects/Intermediate/Cryptocurrency-Finder/src/App.css
  React-JS-Projects/Intermediate/Cryptocurrency-Finder/src/App.jsx
  React-JS-Projects/Intermediate/Cryptocurrency-Finder/src/main.jsx
  React-JS-Projects/Intermediate/Cryptocurrency-Finder/vite.config.js
  React-JS-Projects/README.md
  database/react.json
Labels: bug 🐛, Requested Changes ⚙️

#216 Product Landing Page
  Front-end-Projects/Intermediate/Product-Landing-Page/README.md
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/bg.jpg
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/contact.jpg
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/facebook.png
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/freeshipping.png
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/gift.jpg
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/image.png
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/instagram.png
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/people.jpg
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/people2.jpg
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/people3.jpg
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/search.png
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/shoe.png
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/shoe2.png
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/shoe3.png
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/shoe4.png
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/shoe5.png
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/shoe6.jpg
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/shoe7.png
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/sneakers.png
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/twitter.png
  Front-end-Projects/Intermediate/Product-Landing-Page/assests/whatsapp.png
  Front-end-Projects/Intermediate/Product-Landing-Page/index.html
  Front-end-Projects/Intermediate/Product-Landing-Page/screenshot.webp
  Front-end-Projects/Intermediate/Product-Landing-Page/screenshot2.webp
  Front-end-Projects/Intermediate/Product-Landing-Page/screenshot3.webp
  Front-end-Projects/Intermediate/Product-Landing-Page/script.js
  Front-end-Projects/Intermediate/Product-Landing-Page/styles.css
  Front-end-Projects/README.md
Labels: Requested Changes ⚙️
