Repository Code-A2Z/code-a2z, pull requests merged in 2024-07, with the labels that each got.

#419 Train booking website
  Angular-JS-Projects/Intermediate/Train-Website/.editorconfig
  Angular-JS-Projects/Intermediate/Train-Website/.gitignore
  Angular-JS-Projects/Intermediate/Train-Website/README.md
  Angular-JS-Projects/Intermediate/Train-Website/angular.json
  Angular-JS-Projects/Intermediate/Train-Website/package.json
  Angular-JS-Projects/Intermediate/Train-Website/proxy.conf.json
  Angular-JS-Projects/Intermediate/Train-Website/public/favicon.ico
  Angular-JS-Projects/Intermediate/Train-Website/screenshot.webp
  Angular-JS-Projects/Intermediate/Train-Website/server.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/app.component.css
  Angular-JS-Projects/Intermediate/Train-Website/src/app/app.component.html
  Angular-JS-Projects/Intermediate/Train-Website/src/app/app.component.spec.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/app.component.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/app.config.server.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/app.config.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/app.routes.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/constants/constants.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/models/stations.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/admin/admin.component.css
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/admin/admin.component.html
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/admin/admin.component.spec.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/admin/admin.component.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/bookings/bookings.component.css
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/bookings/bookings.component.html
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/bookings/bookings.component.spec.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/bookings/bookings.component.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/home/home.component.css
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/home/home.component.html
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/home/home.component.spec.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/home/home.component.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/search/search.component.css
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/search/search.component.html
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/search/search.component.spec.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/search/search.component.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/trains/trains.component.css
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/trains/trains.component.html
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/trains/trains.component.spec.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/pages/trains/trains.component.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/services/stations.service.spec.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/services/stations.service.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/services/trains.service.spec.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/app/services/trains.service.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/environments/environment.development.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/environments/environment.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/index.html
  Angular-JS-Projects/Intermediate/Train-Website/src/main.server.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/main.ts
  Angular-JS-Projects/Intermediate/Train-Website/src/styles.css
  Angular-JS-Projects/Intermediate/Train-Website/tsconfig.app.json
  Angular-JS-Projects/Intermediate/Train-Website/tsconfig.json
  Angular-JS-Projects/Intermediate/Train-Website/tsconfig.spec.json
  Angular-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#423 Drag-and-Drop project added
  Vanilla-JS-Projects/Intermediate/Drag-and-Drop/README.md
  Vanilla-JS-Projects/Intermediate/Drag-and-Drop/images/grid-outline.svg
  Vanilla-JS-Projects/Intermediate/Drag-and-Drop/index.html
  Vanilla-JS-Projects/Intermediate/Drag-and-Drop/screenshot.webp
  Vanilla-JS-Projects/Intermediate/Drag-and-Drop/script.js
  Vanilla-JS-Projects/Intermediate/Drag-and-Drop/style.css
  Vanilla-JS-Projects/README.md
  database/vanilla.json
Labels: bug 🐛, Requested Changes ⚙️

#427 Added React.js form validation project
  React-JS-Projects/Intermediate/Form-Validation/README.md
  React-JS-Projects/Intermediate/Form-Validation/package.json
  React-JS-Projects/Intermediate/Form-Validation/public/index.html
  React-JS-Projects/Intermediate/Form-Validation/screenshot.webp
  React-JS-Projects/Intermediate/Form-Validation/src/components/App.css
  React-JS-Projects/Intermediate/Form-Validation/src/components/App.js
  React-JS-Projects/Intermediate/Form-Validation/src/index.js
  React-JS-Projects/README.md
  database/react.json
Labels: Requested Changes ⚙️

#434 Added Pangram Checker: #406
  Vanilla-JS-Projects/Basic/Pangram-Checker/README.md
  Vanilla-JS-Projects/Basic/Pangram-Checker/index.html
  Vanilla-JS-Projects/Basic/Pangram-Checker/screenshot.webp
  Vanilla-JS-Projects/Basic/Pangram-Checker/script.js
  Vanilla-JS-Projects/Basic/Pangram-Checker/style.css
  Vanilla-JS-Projects/README.md
Labels: Requested Changes ⚙️

#461 Animated Tea Cup
  Front-end-Projects/Basic/Animated-Tea-Cup/README.md
  Front-end-Projects/Basic/Animated-Tea-Cup/index.html
  Front-end-Projects/Basic/Animated-Tea-Cup/screenshot.webp
  Front-end-Projects/Basic/Animated-Tea-Cup/style.css
  Front-end-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#470 Google drive
  Front-end-Projects/Basic/Google-Drive-Clone/README.md
  Front-end-Projects/Basic/Google-Drive-Clone/index.html
  Front-end-Projects/Basic/Google-Drive-Clone/screenshot.webp
  Front-end-Projects/Basic/Google-Drive-Clone/style.css
  Front-end-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#485 Interactive drawing website
  Vanilla-JS-Projects/Intermediate/Interactive-Drawing-Website/README.md
  Vanilla-JS-Projects/Intermediate/Interactive-Drawing-Website/image.png
  Vanilla-JS-Projects/Intermediate/Interactive-Drawing-Website/index.html
  Vanilla-JS-Projects/Intermediate/Interactive-Drawing-Website/screenshot.webp
  Vanilla-JS-Projects/Intermediate/Interactive-Drawing-Website/script.js
  Vanilla-JS-Projects/Intermediate/Interactive-Drawing-Website/styles.css
  Vanilla-JS-Projects/README.md
Labels: Requested Changes ⚙️

#476 Added Synonym-Searcher
  Vanilla-JS-Projects/Intermediate/Synonym-Searcher/README.md
  Vanilla-JS-Projects/Intermediate/Synonym-Searcher/app.js
  Vanilla-JS-Projects/Intermediate/Synonym-Searcher/assets/spinner.svg
  Vanilla-JS-Projects/Intermediate/Synonym-Searcher/index.html
  Vanilla-JS-Projects/Intermediate/Synonym-Searcher/main.css
  Vanilla-JS-Projects/Intermediate/Synonym-Searcher/screenshot.webp
  Vanilla-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#491 Added Apna-College-Clone
  Vanilla-JS-Projects/Basic/Apna-College-Clone/README.md
  Vanilla-JS-Projects/Basic/Apna-College-Clone/img/logo.png
  Vanilla-JS-Projects/Basic/Apna-College-Clone/img/sradha.jpg
  Vanilla-JS-Projects/Basic/Apna-College-Clone/index.html
  Vanilla-JS-Projects/Basic/Apna-College-Clone/screenshot.webp
  Vanilla-JS-Projects/Basic/Apna-College-Clone/script.js
  Vanilla-JS-Projects/Basic/Apna-College-Clone/style.css
  Vanilla-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#506 Quote generator
  Vue-JS-Projects/Basic/Quote-Generator/README.md
  Vue-JS-Projects/Basic/Quote-Generator/image/pen-fancy-solid.svg
  Vue-JS-Projects/Basic/Quote-Generator/image/pointer.png
  Vue-JS-Projects/Basic/Quote-Generator/image/quote-machine.png
  Vue-JS-Projects/Basic/Quote-Generator/image/quote_paper.png
  Vue-JS-Projects/Basic/Quote-Generator/image/sad.png
  Vue-JS-Projects/Basic/Quote-Generator/image/screenshot.png
  Vue-JS-Projects/Basic/Quote-Generator/image/wave.svg
  Vue-JS-Projects/Basic/Quote-Generator/index.html
  Vue-JS-Projects/Basic/Quote-Generator/screenshot.webp
  Vue-JS-Projects/Basic/Quote-Generator/script/main.js
  Vue-JS-Projects/Basic/Quote-Generator/script/quotes.js
  Vue-JS-Projects/Basic/Quote-Generator/style/main.css
  Vue-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#516 Added IP-Address Tracker React js Project
  React-JS-Projects/Advanced/IP-Address-Tracker/README.md
  React-JS-Projects/Advanced/IP-Address-Tracker/package.json
  React-JS-Projects/Advanced/IP-Address-Tracker/public/favicon-32x32.png
  React-JS-Projects/Advanced/IP-Address-Tracker/public/favicon.ico
  React-JS-Projects/Advanced/IP-Address-Tracker/public/index.html
  React-JS-Projects/Advanced/IP-Address-Tracker/public/logo192.png
  React-JS-Projects/Advanced/IP-Address-Tracker/public/logo512.png
  React-JS-Projects/Advanced/IP-Address-Tracker/public/manifest.json
  React-JS-Projects/Advanced/IP-Address-Tracker/public/robots.txt
  React-JS-Projects/Advanced/IP-Address-Tracker/screenshot.webp
  React-JS-Projects/Advanced/IP-Address-Tracker/src/App.css
  React-JS-Projects/Advanced/IP-Address-Tracker/src/App.js
  React-JS-Projects/Advanced/IP-Address-Tracker/src/App.test.js
  React-JS-Projects/Advanced/IP-Address-Tracker/src/fonts/Rubik/OFL.txt
  React-JS-Projects/Advanced/IP-Address-Tracker/src/fonts/Rubik/README.txt
  React-JS-Projects/Advanced/IP-Address-Tracker/src/fonts/Rubik/Rubik-Italic-VariableFont_wght.ttf
  React-JS-Projects/Advanced/IP-Address-Tracker/src/fonts/Rubik/Rubik-VariableFont_wght.ttf
  React-JS-Projects/Advanced/IP-Address-Tracker/src/fonts/Rubik/static/Rubik-Black.ttf
  React-JS-Projects/Advanced/IP-Address-Tracker/src/fonts/Rubik/static/Rubik-BlackItalic.ttf
  React-JS-Projects/Advanced/IP-Address-Tracker/src/fonts/Rubik/static/Rubik-Bold.ttf
  React-JS-Projects/Advanced/IP-Address-Tracker/src/fonts/Rubik/static/Rubik-BoldItalic.ttf
  React-JS-Projects/Advanced/IP-Address-Tracker/src/fonts/Rubik/static/Rubik-ExtraBold.ttf
  React-JS-Projects/Advanced/IP-Address-Tracker/src/fonts/Rubik/static/Rubik-ExtraBoldItalic.ttf
  React-JS-Projects/Advanced/IP-Address-Tracker/src/fonts/Rubik/static/Rubik-Italic.ttf
  React-JS-Projects/Advanced/IP-Address-Tracker/src/fonts/Rubik/static/Rubik-Light.ttf
  React-JS-Projects/Advanced/IP-Address-Tracker/src/fonts/Rubik/static/Rubik-LightItalic.ttf
  React-JS-Projects/Advanced/IP-Address-Tracker/src/fonts/Rubik/static/Rubik-Medium.ttf
  React-JS-Projects/Advanced/IP-Address-Tracker/src/fonts/Rubik/static/Rubik-MediumItalic.ttf
  React-JS-Projects/Advanced/IP-Address-Tracker/src/fonts/Rubik/static/Rubik-Regular.ttf
  React-JS-Projects/Advanced/IP-Address-Tracker/src/fonts/Rubik/static/Rubik-SemiBold.ttf
  React-JS-Projects/Advanced/IP-Address-Tracker/src/fonts/Rubik/static/Rubik-SemiBoldItalic.ttf
  React-JS-Projects/Advanced/IP-Address-Tracker/src/images/icon-arrow.svg
  React-JS-Projects/Advanced/IP-Address-Tracker/src/images/icon-location.svg
  React-JS-Projects/Advanced/IP-Address-Tracker/src/images/pattern-bg.png
  React-JS-Projects/Advanced/IP-Address-Tracker/src/index.css
  React-JS-Projects/Advanced/IP-Address-Tracker/src/index.js
  React-JS-Projects/Advanced/IP-Address-Tracker/src/reportWebVitals.js
  React-JS-Projects/Advanced/IP-Address-Tracker/src/setupTests.js
  React-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#526 Analog clock
  Vanilla-JS-Projects/Basic/Analog-Clock/README.md
  Vanilla-JS-Projects/Basic/Analog-Clock/index.html
  Vanilla-JS-Projects/Basic/Analog-Clock/index.js
  Vanilla-JS-Projects/Basic/Analog-Clock/screenshot.webp
  Vanilla-JS-Projects/Basic/Analog-Clock/styles.css
  Vanilla-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#527 Added Kanban-Board
  Vanilla-JS-Projects/Intermediate/Kanban-Board/README.md
  Vanilla-JS-Projects/Intermediate/Kanban-Board/index.html
  Vanilla-JS-Projects/Intermediate/Kanban-Board/screenshot.webp
  Vanilla-JS-Projects/Intermediate/Kanban-Board/script.js
  Vanilla-JS-Projects/Intermediate/Kanban-Board/style.css
  Vanilla-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#529 Added World population project in Vanilla JS
  Vanilla-JS-Projects/Basic/World-Population/Assets/Logo.webp
  Vanilla-JS-Projects/Basic/World-Population/Assets/WorldPopGraph.webp
  Vanilla-JS-Projects/Basic/World-Population/Assets/blog-1.jpg
  Vanilla-JS-Projects/Basic/World-Population/Assets/blog-2.jpg
  Vanilla-JS-Projects/Basic/World-Population/Assets/blog-3.jpg
  Vanilla-JS-Projects/Basic/World-Population/Assets/blog-4.jpg
  Vanilla-JS-Projects/Basic/World-Population/Assets/pop_control.webp
  Vanilla-JS-Projects/Basic/World-Population/Assets/web_script.js
  Vanilla-JS-Projects/Basic/World-Population/Assets/web_style.css
  Vanilla-JS-Projects/Basic/World-Population/README.md
  Vanilla-JS-Projects/Basic/World-Population/index.html
  Vanilla-JS-Projects/Basic/World-Population/predictPopulation.html
  Vanilla-JS-Projects/Basic/World-Population/screenshot.webp
  Vanilla-JS-Projects/Basic/World-Population/script.js
  Vanilla-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#531 Added StopWatch
  Vanilla-JS-Projects/Basic/Stop-Watch/README.md
  Vanilla-JS-Projects/Basic/Stop-Watch/background.jpg
  Vanilla-JS-Projects/Basic/Stop-Watch/index.html
  Vanilla-JS-Projects/Basic/Stop-Watch/screenshot.webp
  Vanilla-JS-Projects/Basic/Stop-Watch/script.js
  Vanilla-JS-Projects/Basic/Stop-Watch/style.css
  Vanilla-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#544 Added Garden planning website
  Vanilla-JS-Projects/Advanced/Garden-Planning-Website/README.md
  Vanilla-JS-Projects/Advanced/Garden-Planning-Website/data.json
  Vanilla-JS-Projects/Advanced/Garden-Planning-Website/image.png
  Vanilla-JS-Projects/Advanced/Garden-Planning-Website/index.html
  Vanilla-JS-Projects/Advanced/Garden-Planning-Website/screenshot.webp
  Vanilla-JS-Projects/Advanced/Garden-Planning-Website/script.js
  Vanilla-JS-Projects/Advanced/Garden-Planning-Website/style.css
  Vanilla-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#538 Added Substrings Checker: #514
  Vanilla-JS-Projects/Basic/Substring-Checker/README.md
  Vanilla-JS-Projects/Basic/Substring-Checker/index.html
  Vanilla-JS-Projects/Basic/Substring-Checker/screenshot.webp
  Vanilla-JS-Projects/Basic/Substring-Checker/script.js
  Vanilla-JS-Projects/Basic/Substring-Checker/style.css
  Vanilla-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#550 Added Zomato Clone(frontend)
  Vanilla-JS-Projects/Intermediate/Zomato-Clone/README.md
  Vanilla-JS-Projects/Intermediate/Zomato-Clone/images/cake-1971552_1280.jpg
  Vanilla-JS-Projects/Intermediate/Zomato-Clone/images/pizza-3010062_1280.jpg
  Vanilla-JS-Projects/Intermediate/Zomato-Clone/images/strawberry-dessert-2191973_1280.jpg
  Vanilla-JS-Projects/Intermediate/Zomato-Clone/index.html
  Vanilla-JS-Projects/Intermediate/Zomato-Clone/screenshot.webp
  Vanilla-JS-Projects/Intermediate/Zomato-Clone/script.js
  Vanilla-JS-Projects/Intermediate/Zomato-Clone/style.css
  Vanilla-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#559 LoginSignupForm
  Front-end-Projects/Basic/Login-Signup-Form/README.md
  Front-end-Projects/Basic/Login-Signup-Form/background.jpg
  Front-end-Projects/Basic/Login-Signup-Form/index.html
  Front-end-Projects/Basic/Login-Signup-Form/screenshot.webp
  Front-end-Projects/Basic/Login-Signup-Form/styles.css
  Front-end-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#553 Added Countries over the world
  Vanilla-JS-Projects/Intermediate/Countries-Over-The-World/README.md
  Vanilla-JS-Projects/Intermediate/Countries-Over-The-World/index.html
  Vanilla-JS-Projects/Intermediate/Countries-Over-The-World/screenshot.webp
  Vanilla-JS-Projects/Intermediate/Countries-Over-The-World/script.js
  Vanilla-JS-Projects/Intermediate/Countries-Over-The-World/style.css
  Vanilla-JS-Projects/README.md
Labels: Requested Changes ⚙️

#569 Expense Splitter Website
  Vanilla-JS-Projects/Intermediate/Expense-Splitter-Website/README.md
  Vanilla-JS-Projects/Intermediate/Expense-Splitter-Website/index.html
  Vanilla-JS-Projects/Intermediate/Expense-Splitter-Website/screenshot.webp
  Vanilla-JS-Projects/Intermediate/Expense-Splitter-Website/script.js
  Vanilla-JS-Projects/Intermediate/Expense-Splitter-Website/styles.css
  Vanilla-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#552 Added Random-Picker
  Vanilla-JS-Projects/Basic/Random-Picker/README.md
  Vanilla-JS-Projects/Basic/Random-Picker/index.html
  Vanilla-JS-Projects/Basic/Random-Picker/screenshot.webp
  Vanilla-JS-Projects/Basic/Random-Picker/script.js
  Vanilla-JS-Projects/Basic/Random-Picker/style.css
  Vanilla-JS-Projects/README.md
Labels: Requested Changes ⚙️

#603 Added: Vocabulary Builder (Vanilla JS)
  Vanilla-JS-Projects/Advanced/Vocabulary-Builder/README.md
  Vanilla-JS-Projects/Advanced/Vocabulary-Builder/index.html
  Vanilla-JS-Projects/Advanced/Vocabulary-Builder/screenshot.webp
  Vanilla-JS-Projects/Advanced/Vocabulary-Builder/script.js
  Vanilla-JS-Projects/Advanced/Vocabulary-Builder/style.css
  Vanilla-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#608 Feat: Swiggy clone is added
  React-JS-Projects/Basic/Swiggy-Clone/.eslintrc.cjs
  React-JS-Projects/Basic/Swiggy-Clone/README.md
  React-JS-Projects/Basic/Swiggy-Clone/index.html
  React-JS-Projects/Basic/Swiggy-Clone/package.json
  React-JS-Projects/Basic/Swiggy-Clone/postcss.config.js
  React-JS-Projects/Basic/Swiggy-Clone/public/vite.svg
  React-JS-Projects/Basic/Swiggy-Clone/screenshot.webp
  React-JS-Projects/Basic/Swiggy-Clone/src/App.jsx
  React-JS-Projects/Basic/Swiggy-Clone/src/Components/Chain.jsx
  React-JS-Projects/Basic/Swiggy-Clone/src/Components/Cuisines.jsx
  React-JS-Projects/Basic/Swiggy-Clone/src/Components/Footer.jsx
  React-JS-Projects/Basic/Swiggy-Clone/src/Components/Hero.jsx
  React-JS-Projects/Basic/Swiggy-Clone/src/Components/MobileBar.jsx
  React-JS-Projects/Basic/Swiggy-Clone/src/Components/Navbar.jsx
  React-JS-Projects/Basic/Swiggy-Clone/src/Components/Playstore.jsx
  React-JS-Projects/Basic/Swiggy-Clone/src/assets/icon.png
  React-JS-Projects/Basic/Swiggy-Clone/src/index.css
  React-JS-Projects/Basic/Swiggy-Clone/src/main.jsx
  React-JS-Projects/Basic/Swiggy-Clone/tailwind.config.js
  React-JS-Projects/Basic/Swiggy-Clone/vite.config.js
  React-JS-Projects/Basic/Swiggy-Clone/webpack.config.js
  React-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#621 3D Solar-System
  Vanilla-JS-Projects/Basic/3D-Solar-System/README.md
  Vanilla-JS-Projects/Basic/3D-Solar-System/index.html
  Vanilla-JS-Projects/Basic/3D-Solar-System/screenshot.webp
  Vanilla-JS-Projects/Basic/3D-Solar-System/script.js
  Vanilla-JS-Projects/Basic/3D-Solar-System/style.css
  Vanilla-JS-Projects/README.md
Labels: Requested Changes ⚙️

#633 Shopping cart - React redux
  React-JS-Projects/Basic/Shopping-Cart/README.md
  React-JS-Projects/Basic/Shopping-Cart/images/cart.png
  React-JS-Projects/Basic/Shopping-Cart/images/product-listing.png
  React-JS-Projects/Basic/Shopping-Cart/index.html
  React-JS-Projects/Basic/Shopping-Cart/package.json
  React-JS-Projects/Basic/Shopping-Cart/postcss.config.js
  React-JS-Projects/Basic/Shopping-Cart/screenshot.webp
  React-JS-Projects/Basic/Shopping-Cart/src/App.jsx
  React-JS-Projects/Basic/Shopping-Cart/src/components/CartItem.jsx
  React-JS-Projects/Basic/Shopping-Cart/src/components/EmptyCart.jsx
  React-JS-Projects/Basic/Shopping-Cart/src/components/ProductCard.jsx
  React-JS-Projects/Basic/Shopping-Cart/src/index.css
  React-JS-Projects/Basic/Shopping-Cart/src/main.jsx
  React-JS-Projects/Basic/Shopping-Cart/src/pages/Cart.jsx
  React-JS-Projects/Basic/Shopping-Cart/src/pages/Products.jsx
  React-JS-Projects/Basic/Shopping-Cart/src/redux/CartSlice.jsx
  React-JS-Projects/Basic/Shopping-Cart/src/redux/Store.jsx
  React-JS-Projects/Basic/Shopping-Cart/tailwind.config.js
  React-JS-Projects/Basic/Shopping-Cart/vite.config.js
  React-JS-Projects/README.md
Labels: level1, Approved ✔️, React-JS 😍, gssoc

#626 Added Co-Prime Number Checker: #623
  Vanilla-JS-Projects/Basic/Co-Prime-Number-Checker/README.md
  Vanilla-JS-Projects/Basic/Co-Prime-Number-Checker/index.html
  Vanilla-JS-Projects/Basic/Co-Prime-Number-Checker/screenshot.webp
  Vanilla-JS-Projects/Basic/Co-Prime-Number-Checker/script.js
  Vanilla-JS-Projects/Basic/Co-Prime-Number-Checker/style.css
  Vanilla-JS-Projects/README.md
Labels: Requested Changes ⚙️

#634 Added Vowel Counter
  Vanilla-JS-Projects/Basic/Vowel-Counter/README.md
  Vanilla-JS-Projects/Basic/Vowel-Counter/index.html
  Vanilla-JS-Projects/Basic/Vowel-Counter/screenshot.webp
  Vanilla-JS-Projects/Basic/Vowel-Counter/script.js
  Vanilla-JS-Projects/Basic/Vowel-Counter/style.css
  Vanilla-JS-Projects/README.md
Labels: Requested Changes ⚙️

#629 Added Youtube-Clone
  Vanilla-JS-Projects/Basic/Youtube-Clone/README.md
  Vanilla-JS-Projects/Basic/Youtube-Clone/img/bell.PNG
  Vanilla-JS-Projects/Basic/Youtube-Clone/img/explore.PNG
  Vanilla-JS-Projects/Basic/Youtube-Clone/img/grid.PNG
  Vanilla-JS-Projects/Basic/Youtube-Clone/img/history.PNG
  Vanilla-JS-Projects/Basic/Youtube-Clone/img/home.PNG
  Vanilla-JS-Projects/Basic/Youtube-Clone/img/library.PNG
  Vanilla-JS-Projects/Basic/Youtube-Clone/img/liked video.PNG
  Vanilla-JS-Projects/Basic/Youtube-Clone/img/logo.PNG
  Vanilla-JS-Projects/Basic/Youtube-Clone/img/profile-pic.png
  Vanilla-JS-Projects/Basic/Youtube-Clone/img/search.PNG
  Vanilla-JS-Projects/Basic/Youtube-Clone/img/show more.PNG
  Vanilla-JS-Projects/Basic/Youtube-Clone/img/subscription.PNG
  Vanilla-JS-Projects/Basic/Youtube-Clone/img/video.PNG
  Vanilla-JS-Projects/Basic/Youtube-Clone/img/watch-later.PNG
  Vanilla-JS-Projects/Basic/Youtube-Clone/img/your-video.PNG
  Vanilla-JS-Projects/Basic/Youtube-Clone/index.html
  Vanilla-JS-Projects/Basic/Youtube-Clone/screenshot.webp
  Vanilla-JS-Projects/Basic/Youtube-Clone/script.js
  Vanilla-JS-Projects/Basic/Youtube-Clone/style.css
  Vanilla-JS-Projects/README.md
Labels: Requested Changes ⚙️

#649 Custom video player
  Vanilla-JS-Projects/Basic/Custom-Video-Player/README.md
  Vanilla-JS-Projects/Basic/Custom-Video-Player/css/progress.css
  Vanilla-JS-Projects/Basic/Custom-Video-Player/css/style.css
  Vanilla-JS-Projects/Basic/Custom-Video-Player/img/poster.png
  Vanilla-JS-Projects/Basic/Custom-Video-Player/index.html
  Vanilla-JS-Projects/Basic/Custom-Video-Player/screenshot.webp
  Vanilla-JS-Projects/Basic/Custom-Video-Player/script.js
  Vanilla-JS-Projects/README.md
Labels: Requested Changes ⚙️

#620 added expense tracker in vuejs
  Vue-JS-Projects/Intermediate/Expense-Tracker/README.md
  Vue-JS-Projects/Intermediate/Expense-Tracker/index.html
  Vue-JS-Projects/Intermediate/Expense-Tracker/package.json
  Vue-JS-Projects/Intermediate/Expense-Tracker/public/favicon.ico
  Vue-JS-Projects/Intermediate/Expense-Tracker/public/screen.png
  Vue-JS-Projects/Intermediate/Expense-Tracker/screenshot.webp
  Vue-JS-Projects/Intermediate/Expense-Tracker/src/App.vue
  Vue-JS-Projects/Intermediate/Expense-Tracker/src/assets/style.css
  Vue-JS-Projects/Intermediate/Expense-Tracker/src/components/AddTransaction.vue
  Vue-JS-Projects/Intermediate/Expense-Tracker/src/components/Balance.vue
  Vue-JS-Projects/Intermediate/Expense-Tracker/src/components/Header.vue
  Vue-JS-Projects/Intermediate/Expense-Tracker/src/components/IncomeExpenses.vue
  Vue-JS-Projects/Intermediate/Expense-Tracker/src/components/TransactionList.vue
  Vue-JS-Projects/Intermediate/Expense-Tracker/src/main.js
  Vue-JS-Projects/Intermediate/Expense-Tracker/vite.config.js
  Vue-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#665 added tesla clone
  React-JS-Projects/Intermediate/Tesla-Clone/README.md
  React-JS-Projects/Intermediate/Tesla-Clone/package.json
  React-JS-Projects/Intermediate/Tesla-Clone/public/favicon.ico
  React-JS-Projects/Intermediate/Tesla-Clone/public/images/accessories.jpg
  React-JS-Projects/Intermediate/Tesla-Clone/public/images/audio.jpg
  React-JS-Projects/Intermediate/Tesla-Clone/public/images/connected.jpg
  React-JS-Projects/Intermediate/Tesla-Clone/public/images/down-arrow.svg
  React-JS-Projects/Intermediate/Tesla-Clone/public/images/favicon.ico
  React-JS-Projects/Intermediate/Tesla-Clone/public/images/game.jpg
  React-JS-Projects/Intermediate/Tesla-Clone/public/images/logo.svg
  React-JS-Projects/Intermediate/Tesla-Clone/public/images/model-3.jpg
  React-JS-Projects/Intermediate/Tesla-Clone/public/images/model-s.jpg
  React-JS-Projects/Intermediate/Tesla-Clone/public/images/model-x.jpg
  React-JS-Projects/Intermediate/Tesla-Clone/public/images/model-y.jpg
  React-JS-Projects/Intermediate/Tesla-Clone/public/images/new-interior.jpg
  React-JS-Projects/Intermediate/Tesla-Clone/public/images/solar-panel.jpg
  React-JS-Projects/Intermediate/Tesla-Clone/public/images/solar-roof.jpg
  React-JS-Projects/Intermediate/Tesla-Clone/public/index.html
  React-JS-Projects/Intermediate/Tesla-Clone/public/logo192.png
  React-JS-Projects/Intermediate/Tesla-Clone/public/logo512.png
  React-JS-Projects/Intermediate/Tesla-Clone/public/manifest.json
  React-JS-Projects/Intermediate/Tesla-Clone/public/robots.txt
  React-JS-Projects/Intermediate/Tesla-Clone/screenshot.webp
  React-JS-Projects/Intermediate/Tesla-Clone/src/App.css
  React-JS-Projects/Intermediate/Tesla-Clone/src/App.js
  React-JS-Projects/Intermediate/Tesla-Clone/src/App.test.js
  React-JS-Projects/Intermediate/Tesla-Clone/src/app/store.js
  React-JS-Projects/Intermediate/Tesla-Clone/src/components/Header.js
  React-JS-Projects/Intermediate/Tesla-Clone/src/components/Home.js
  React-JS-Projects/Intermediate/Tesla-Clone/src/components/Section.js
  React-JS-Projects/Intermediate/Tesla-Clone/src/features/car/carSlice.js
  React-JS-Projects/Intermediate/Tesla-Clone/src/index.css
  React-JS-Projects/Intermediate/Tesla-Clone/src/index.js
  React-JS-Projects/Intermediate/Tesla-Clone/src/logo.svg
  React-JS-Projects/Intermediate/Tesla-Clone/src/reportWebVitals.js
  React-JS-Projects/Intermediate/Tesla-Clone/src/setupTests.js
  React-JS-Projects/Intermediate/Tesla-Clone/yarn.lock
  React-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️, Follow Guidelines ✒️

#671 To do list - Typescript
  Typescript-Projects/Advanced/To-Do-List-App/README.md
  Typescript-Projects/Advanced/To-Do-List-App/images/all.png
  Typescript-Projects/Advanced/To-Do-List-App/images/completed.png
  Typescript-Projects/Advanced/To-Do-List-App/images/edittask.png
  Typescript-Projects/Advanced/To-Do-List-App/images/inprogress.png
  Typescript-Projects/Advanced/To-Do-List-App/images/newtask.png
  Typescript-Projects/Advanced/To-Do-List-App/images/working_video.mp4
  Typescript-Projects/Advanced/To-Do-List-App/index.html
  Typescript-Projects/Advanced/To-Do-List-App/package.json
  Typescript-Projects/Advanced/To-Do-List-App/postcss.config.js
  Typescript-Projects/Advanced/To-Do-List-App/screenshot.webp
  Typescript-Projects/Advanced/To-Do-List-App/src/App.tsx
  Typescript-Projects/Advanced/To-Do-List-App/src/Types/Task.ts
  Typescript-Projects/Advanced/To-Do-List-App/src/components/AddTask.tsx
  Typescript-Projects/Advanced/To-Do-List-App/src/components/EditTask.tsx
  Typescript-Projects/Advanced/To-Do-List-App/src/components/TaskEmpty.jsx
  Typescript-Projects/Advanced/To-Do-List-App/src/components/TaskList.tsx
  Typescript-Projects/Advanced/To-Do-List-App/src/components/Title.jsx
  Typescript-Projects/Advanced/To-Do-List-App/src/contexts/TaskContext.tsx
  Typescript-Projects/Advanced/To-Do-List-App/src/hooks/UseTasks.tsx
  Typescript-Projects/Advanced/To-Do-List-App/src/index.css
  Typescript-Projects/Advanced/To-Do-List-App/src/main.tsx
  Typescript-Projects/Advanced/To-Do-List-App/src/vite-env.d.ts
  Typescript-Projects/Advanced/To-Do-List-App/tailwind.config.js
  Typescript-Projects/Advanced/To-Do-List-App/tsconfig.app.json
  Typescript-Projects/Advanced/To-Do-List-App/tsconfig.json
  Typescript-Projects/Advanced/To-Do-List-App/tsconfig.node.json
  Typescript-Projects/Advanced/To-Do-List-App/vite.config.ts
  Typescript-Projects/README.md
Labels: Requested Changes ⚙️

#580 Added Password Manager
  Vanilla-JS-Projects/Basic/Password-Manager/README.md
  Vanilla-JS-Projects/Basic/Password-Manager/index.html
  Vanilla-JS-Projects/Basic/Password-Manager/screenshot.webp
  Vanilla-JS-Projects/Basic/Password-Manager/scripts.js
  Vanilla-JS-Projects/Basic/Password-Manager/styles.css
  Vanilla-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#619 Nodemailer Mail sender
  Node-JS-Projects/Intermediate/Gmail-Nodemailer/app.js
  Node-JS-Projects/Intermediate/Gmail-Nodemailer/package.json
  Node-JS-Projects/Intermediate/Gmail-Nodemailer/public/mail.css
  Node-JS-Projects/Intermediate/Gmail-Nodemailer/public/mail.html
  Node-JS-Projects/Intermediate/Gmail-Nodemailer/readme.md
  Node-JS-Projects/Intermediate/Gmail-Nodemailer/screenshot.webp
  Node-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️, Follow Guidelines ✒️

#674 Added Wheel-Selector
  Vanilla-JS-Projects/Intermediate/Wheel-Selector/README.md
  Vanilla-JS-Projects/Intermediate/Wheel-Selector/index.html
  Vanilla-JS-Projects/Intermediate/Wheel-Selector/screenshot.webp
  Vanilla-JS-Projects/Intermediate/Wheel-Selector/script.js
  Vanilla-JS-Projects/Intermediate/Wheel-Selector/style.css
  Vanilla-JS-Projects/README.md
Labels: question❓, Requested Changes ⚙️

#678 Corrected the isogram string project .
  Vanilla-JS-Projects/Basic/Isogram-Checker/index.html
  Vanilla-JS-Projects/Basic/Isogram-Checker/script.js
Labels: bug 🐛, Requested Changes ⚙️

#679 Book Review Website
  Vanilla-JS-Projects/Intermediate/Book-Review-Website/README.md
  Vanilla-JS-Projects/Intermediate/Book-Review-Website/index.html
  Vanilla-JS-Projects/Intermediate/Book-Review-Website/screenshot.webp
  Vanilla-JS-Projects/Intermediate/Book-Review-Website/script.js
  Vanilla-JS-Projects/Intermediate/Book-Review-Website/styles.css
  Vanilla-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#681 added Breaking news app
  Next-JS-Projects/Advanced/Breaking-News-App/.eslintrc.json
  Next-JS-Projects/Advanced/Breaking-News-App/README.md
  Next-JS-Projects/Advanced/Breaking-News-App/assets/images/newsarticle_placeholder.png
  Next-JS-Projects/Advanced/Breaking-News-App/components/NavBar.tsx
  Next-JS-Projects/Advanced/Breaking-News-App/components/NewsArticleEntry.tsx
  Next-JS-Projects/Advanced/Breaking-News-App/components/NewsArticlesGrid.tsx
  Next-JS-Projects/Advanced/Breaking-News-App/models/NewsArticles.d.ts
  Next-JS-Projects/Advanced/Breaking-News-App/next.config.js
  Next-JS-Projects/Advanced/Breaking-News-App/package.json
  Next-JS-Projects/Advanced/Breaking-News-App/pages/404.tsx
  Next-JS-Projects/Advanced/Breaking-News-App/pages/500.tsx
  Next-JS-Projects/Advanced/Breaking-News-App/pages/_app.tsx
  Next-JS-Projects/Advanced/Breaking-News-App/pages/_document.tsx
  Next-JS-Projects/Advanced/Breaking-News-App/pages/api/search-news.ts
  Next-JS-Projects/Advanced/Breaking-News-App/pages/categories/[category].tsx
  Next-JS-Projects/Advanced/Breaking-News-App/pages/index.tsx
  Next-JS-Projects/Advanced/Breaking-News-App/pages/search.tsx
  Next-JS-Projects/Advanced/Breaking-News-App/public/favicon.ico
  Next-JS-Projects/Advanced/Breaking-News-App/public/next.svg
  Next-JS-Projects/Advanced/Breaking-News-App/public/vercel.svg
  Next-JS-Projects/Advanced/Breaking-News-App/screenshot.webp
  Next-JS-Projects/Advanced/Breaking-News-App/styles/NewsArticleEntry.module.css
  Next-JS-Projects/Advanced/Breaking-News-App/styles/app.module.css
  Next-JS-Projects/Advanced/Breaking-News-App/styles/globals.css
  Next-JS-Projects/Advanced/Breaking-News-App/tsconfig.json
  Next-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#698 Added Dictionary App
  Vanilla-JS-Projects/Basic/Dictionary-App/README.md
  Vanilla-JS-Projects/Basic/Dictionary-App/index.html
  Vanilla-JS-Projects/Basic/Dictionary-App/screenshot.webp
  Vanilla-JS-Projects/Basic/Dictionary-App/script.js
  Vanilla-JS-Projects/Basic/Dictionary-App/style.css
  Vanilla-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️
