Repository Code-A2Z/code-a2z, pull requests merged in 2024-08, with the labels that each got.

#683 Added: Hackathon Tracker (VanillaJS)
  Vanilla-JS-Projects/Advanced/Hackathon-Tracker/README.md
  Vanilla-JS-Projects/Advanced/Hackathon-Tracker/index.html
  Vanilla-JS-Projects/Advanced/Hackathon-Tracker/screenshot.webp
  Vanilla-JS-Projects/Advanced/Hackathon-Tracker/script.js
  Vanilla-JS-Projects/Advanced/Hackathon-Tracker/style.css
  Vanilla-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️, Follow Guidelines ✒️

#692 User registration system using node js
  Node-JS-Projects/Advanced/User-Registration-System/README.md
  Node-JS-Projects/Advanced/User-Registration-System/backend/app.js
  Node-JS-Projects/Advanced/User-Registration-System/backend/config/dbConnection.js
  Node-JS-Projects/Advanced/User-Registration-System/backend/controllers/AuthController.js
  Node-JS-Projects/Advanced/User-Registration-System/backend/middlewares/validator.js
  Node-JS-Projects/Advanced/User-Registration-System/backend/models/User.js
  Node-JS-Projects/Advanced/User-Registration-System/backend/package.json
  Node-JS-Projects/Advanced/User-Registration-System/backend/routes/AuthRoutes.js
  Node-JS-Projects/Advanced/User-Registration-System/backend/utils/jwt.js
  Node-JS-Projects/Advanced/User-Registration-System/backend/utils/otp.js
  Node-JS-Projects/Advanced/User-Registration-System/frontend/Login.html
  Node-JS-Projects/Advanced/User-Registration-System/frontend/Register.html
  Node-JS-Projects/Advanced/User-Registration-System/frontend/index.html
  Node-JS-Projects/Advanced/User-Registration-System/frontend/js/login.js
  Node-JS-Projects/Advanced/User-Registration-System/frontend/js/profile.js
  Node-JS-Projects/Advanced/User-Registration-System/frontend/js/register.js
  Node-JS-Projects/Advanced/User-Registration-System/frontend/styles/styles.css
  Node-JS-Projects/Advanced/User-Registration-System/images/image01.png
  Node-JS-Projects/Advanced/User-Registration-System/images/image02.png
  Node-JS-Projects/Advanced/User-Registration-System/images/image03.png
  Node-JS-Projects/Advanced/User-Registration-System/images/image04.png
  Node-JS-Projects/Advanced/User-Registration-System/screenshot.webp
  Node-JS-Projects/README.md
Labels: Requested Changes ⚙️

#695 Quiz Application using Typescript
  Typescript-Projects/Intermediate/Quiz-App/.eslintrc.cjs
  Typescript-Projects/Intermediate/Quiz-App/README.md
  Typescript-Projects/Intermediate/Quiz-App/index.html
  Typescript-Projects/Intermediate/Quiz-App/package.json
  Typescript-Projects/Intermediate/Quiz-App/postcss.config.js
  Typescript-Projects/Intermediate/Quiz-App/public/vite.svg
  Typescript-Projects/Intermediate/Quiz-App/screenshot.webp
  Typescript-Projects/Intermediate/Quiz-App/src/App.css
  Typescript-Projects/Intermediate/Quiz-App/src/App.tsx
  Typescript-Projects/Intermediate/Quiz-App/src/Components/Hero.tsx
  Typescript-Projects/Intermediate/Quiz-App/src/Components/Navbar.tsx
  Typescript-Projects/Intermediate/Quiz-App/src/Components/Question.tsx
  Typescript-Projects/Intermediate/Quiz-App/src/Components/Quiz.tsx
  Typescript-Projects/Intermediate/Quiz-App/src/assets/hero.png
  Typescript-Projects/Intermediate/Quiz-App/src/assets/react.svg
  Typescript-Projects/Intermediate/Quiz-App/src/data/questions.json
  Typescript-Projects/Intermediate/Quiz-App/src/index.css
  Typescript-Projects/Intermediate/Quiz-App/src/main.tsx
  Typescript-Projects/Intermediate/Quiz-App/src/vite-env.d.ts
  Typescript-Projects/Intermediate/Quiz-App/tailwind.config.js
  Typescript-Projects/Intermediate/Quiz-App/tsconfig.app.json
  Typescript-Projects/Intermediate/Quiz-App/tsconfig.json
  Typescript-Projects/Intermediate/Quiz-App/tsconfig.node.json
  Typescript-Projects/Intermediate/Quiz-App/vite.config.ts
  Typescript-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#757 Added: Attendance Tracker Next.js
  Next-JS-Projects/Advanced/Attendance-Tracking-App/.env.sample
  Next-JS-Projects/Advanced/Attendance-Tracking-App/.eslintrc.json
  Next-JS-Projects/Advanced/Attendance-Tracking-App/README.md
  Next-JS-Projects/Advanced/Attendance-Tracking-App/app/(root)/(home)/page.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/app/(root)/calendar/page.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/app/(root)/layout.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/app/(root)/settings/dsa/page.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/app/(root)/settings/layout.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/app/(root)/settings/page.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/app/favicon.ico
  Next-JS-Projects/Advanced/Attendance-Tracking-App/app/globals.css
  Next-JS-Projects/Advanced/Attendance-Tracking-App/app/layout.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/firebase/config.ts
  Next-JS-Projects/Advanced/Attendance-Tracking-App/next.config.mjs
  Next-JS-Projects/Advanced/Attendance-Tracking-App/package.json
  Next-JS-Projects/Advanced/Attendance-Tracking-App/postcss.config.mjs
  Next-JS-Projects/Advanced/Attendance-Tracking-App/public/assets/images/bottom-float.png
  Next-JS-Projects/Advanced/Attendance-Tracking-App/public/assets/images/logo.png
  Next-JS-Projects/Advanced/Attendance-Tracking-App/public/assets/images/profile.png
  Next-JS-Projects/Advanced/Attendance-Tracking-App/public/assets/images/top-float.png
  Next-JS-Projects/Advanced/Attendance-Tracking-App/screenshot.webp
  Next-JS-Projects/Advanced/Attendance-Tracking-App/src/Components/Calendar/Calendar.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/src/Components/Footer.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/src/Components/Home/EditModal.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/src/Components/Home/Home.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/src/Components/Home/Modal.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/src/Components/Home/SubCard.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/src/Components/Home/percentages.css
  Next-JS-Projects/Advanced/Attendance-Tracking-App/src/Components/Landing.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/src/Components/Navbar.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/src/Components/Settings/ActivityCard.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/src/Components/Settings/ReportCard.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/src/Components/Settings/Settings.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/src/Components/Settings/Stamps.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/src/svg-components/HomeSvg.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/src/svg-components/Logo.tsx
  Next-JS-Projects/Advanced/Attendance-Tracking-App/tailwind.config.ts
  Next-JS-Projects/Advanced/Attendance-Tracking-App/tsconfig.json
  Next-JS-Projects/README.md
Labels: bug 🐛, Requested Changes ⚙️

#759 Movie app
  Vanilla-JS-Projects/Intermediate/Movie-App/README.md
  Vanilla-JS-Projects/Intermediate/Movie-App/api.js
  Vanilla-JS-Projects/Intermediate/Movie-App/index.html
  Vanilla-JS-Projects/Intermediate/Movie-App/main.js
  Vanilla-JS-Projects/Intermediate/Movie-App/screenshot.webp
  Vanilla-JS-Projects/Intermediate/Movie-App/style.css
  Vanilla-JS-Projects/README.md
Labels: Requested Changes ⚙️
