Repository Code-A2Z/code-a2z, pull requests merged in 2025-02, with the labels that each got.

#1066 🧑‍💻: 404 Error page #402
  package-lock.json
  src/app/not-found.tsx
Labels: Status: Review Ongoing

#1064 Amazon clone
  src/app/(category)/README.md
  src/app/(category)/frontend/(projects)/amazon/Readme.md
  src/app/(category)/frontend/(projects)/amazon/amazon.css
  src/app/(category)/frontend/(projects)/amazon/cart.css
  src/app/(category)/frontend/(projects)/amazon/cart.html
  src/app/(category)/frontend/(projects)/amazon/images/amazon_logo.png
  src/app/(category)/frontend/(projects)/amazon/images/box1_image.jpg
  src/app/(category)/frontend/(projects)/amazon/images/box2_image.jpg
  src/app/(category)/frontend/(projects)/amazon/images/box3_image.jpg
  src/app/(category)/frontend/(projects)/amazon/images/box4_image.jpg
  src/app/(category)/frontend/(projects)/amazon/images/box5_image.jpg
  src/app/(category)/frontend/(projects)/amazon/images/box6_image.jpg
  src/app/(category)/frontend/(projects)/amazon/images/box7_image.jpg
  src/app/(category)/frontend/(projects)/amazon/images/box8_image.jpg
  src/app/(category)/frontend/(projects)/amazon/images/d
  src/app/(category)/frontend/(projects)/amazon/images/header1.jpg
  src/app/(category)/frontend/(projects)/amazon/images/header2.jpg
  src/app/(category)/frontend/(projects)/amazon/images/header3.jpg
  src/app/(category)/frontend/(projects)/amazon/images/header4.jpg
  src/app/(category)/frontend/(projects)/amazon/images/header5.jpg
  src/app/(category)/frontend/(projects)/amazon/images/header6.jpg
  src/app/(category)/frontend/(projects)/amazon/images/headphone2.webp
  src/app/(category)/frontend/(projects)/amazon/images/headphone4.jpg
  src/app/(category)/frontend/(projects)/amazon/index.html
  src/app/(category)/frontend/(projects)/amazon/login.css
  src/app/(category)/frontend/(projects)/amazon/login.html
  src/app/(category)/frontend/(projects)/amazon/product.css
  src/app/(category)/frontend/(projects)/amazon/product.html
  src/app/(category)/frontend/(projects)/amazon/screenshot.webp
  src/app/(category)/frontend/(projects)/amazon/script-header.js
  src/database/data.json
Labels: Status: Review Ongoing

#1079 medrecord added (Closes #1078)
  src/app/(category)/README.md
  src/app/(category)/node/(projects)/med-brain/.gitignore
  src/app/(category)/node/(projects)/med-brain/README.md
  src/app/(category)/node/(projects)/med-brain/images/Signup.png
  src/app/(category)/node/(projects)/med-brain/images/login.png
  src/app/(category)/node/(projects)/med-brain/images/logout.png
  src/app/(category)/node/(projects)/med-brain/images/prescription.png
  src/app/(category)/node/(projects)/med-brain/package-lock.json
  src/app/(category)/node/(projects)/med-brain/package.json
  src/app/(category)/node/(projects)/med-brain/screenshot.webp
  src/app/(category)/node/(projects)/med-brain/src/controllers/auth.controllers.js
  src/app/(category)/node/(projects)/med-brain/src/controllers/pres.controllers.js
  src/app/(category)/node/(projects)/med-brain/src/index.js
  src/app/(category)/node/(projects)/med-brain/src/lib/cloudinary.js
  src/app/(category)/node/(projects)/med-brain/src/lib/db.js
  src/app/(category)/node/(projects)/med-brain/src/lib/utils.js
  src/app/(category)/node/(projects)/med-brain/src/middlewares/auth.middleware.js
  src/app/(category)/node/(projects)/med-brain/src/models/presModel.js
  src/app/(category)/node/(projects)/med-brain/src/models/user.model.js
  src/app/(category)/node/(projects)/med-brain/src/routes/auth.route.js
  src/app/(category)/node/(projects)/med-brain/src/routes/pres.route.js
  src/database/data.json
Labels: bug, Status: Requested Changes

#1081 real time chat app added
  src/app/(category)/README.md
  src/app/(category)/node/(projects)/real-time-chat-app/README.md
  src/app/(category)/node/(projects)/real-time-chat-app/images/getmessage.png
  src/app/(category)/node/(projects)/real-time-chat-app/images/login.png
  src/app/(category)/node/(projects)/real-time-chat-app/images/sendmessage.png
  src/app/(category)/node/(projects)/real-time-chat-app/images/signup.png
  src/app/(category)/node/(projects)/real-time-chat-app/package-lock.json
  src/app/(category)/node/(projects)/real-time-chat-app/package.json
  src/app/(category)/node/(projects)/real-time-chat-app/screenshot.webp
  src/app/(category)/node/(projects)/real-time-chat-app/src/controllers/auth.controller.js
  src/app/(category)/node/(projects)/real-time-chat-app/src/controllers/message.controller.js
  src/app/(category)/node/(projects)/real-time-chat-app/src/index.js
  src/app/(category)/node/(projects)/real-time-chat-app/src/lib/cloudinary.js
  src/app/(category)/node/(projects)/real-time-chat-app/src/lib/db.js
  src/app/(category)/node/(projects)/real-time-chat-app/src/lib/socket.js
  src/app/(category)/node/(projects)/real-time-chat-app/src/lib/utils.js
  src/app/(category)/node/(projects)/real-time-chat-app/src/middleware/auth.middleware.js
  src/app/(category)/node/(projects)/real-time-chat-app/src/models/message.model.js
  src/app/(category)/node/(projects)/real-time-chat-app/src/models/user.model.js
  src/app/(category)/node/(projects)/real-time-chat-app/src/routes/auth.route.js
  src/app/(category)/node/(projects)/real-time-chat-app/src/routes/message.route.js
  src/app/(category)/node/(projects)/real-time-chat-app/src/seeds/user.seed.js
  src/database/data.json
Labels: Status: Requested Changes
