Repository Code-A2Z/code-a2z, pull requests merged in 2025-01, with the labels that each got.

#1050 Update Angular & Next Tags
  src/database/data.json
Labels: bug 🐛, Status: Review Ongoing

#1060 #1059 - homepage styled
  src/app/globals.css
  src/app/page.tsx
Labels: Status: Requested Changes

#1061 Added FAQs Section
  src/app/page.tsx
  src/components/shared/FaqsComponent.tsx
Labels: bug 🐛, Status: Requested Changes
